### ISSUE TITLE
macOS Monterey not supported?

### ISSUE THREAD

**Issue by stuffnthingzz** [RomanScott/weMessage#45]
Hello! I am running macOS Monterey, and being told that I have an insignificant version

"
Last login: Wed Sep 22 15:22:42 on ttys000
/Users/dylan/Documents/weServer/run.command ; exit;                             
dylan@Dylans-Air ~ % /Users/dylan/Documents/weServer/run.command ; exit;
 
[INFO] [weServer] weServer only supports Mac OS Yosemite and higher.
[INFO] [weServer] Please update your operating system to use it. Shutting down!
 
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "scott.wemessage.server.g.a.c()" because the return value of "scott.wemessage.server.a.f()" is null
	at scott.wemessage.server.a.h(SourceFile:142)
	at scott.wemessage.server.ServerLauncher.main(SourceFile:10)
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
"

**Comment by geoffrobertson** [comment]
Me too. weServer installation seems to think Monterey is a version earlier than Yosemite.

**Comment by hugos** [comment]
The team is clearly inactive thus the project is pretty much dead.

**Comment by DevHalpin** [comment]
You can change the MIN_OS_VERSION so it looks at the major version number instead of the minor and it works on Monterey.  Just did it to test and was able to connect and send messages using my mac with the latest Monterey version

**Comment by hugos** [comment]
There's absolutely no need for that. The team behind it is inactive as I previously said.

Google "Air Message" same as wemessage but 2x better and easy to use.

Your welcome.

**Comment by DevHalpin** [comment]
Adding that bit about Air Message would have saved me some time there haha.  Oh well, it was an interesting experience learning how to compile this app so no harm there.  Still going to install Air Message instead since it's active.  Thanks @hugos

**Comment by hugos** [comment]
You're welcome! I honestly just found out about it, been using it for 2 weeks and it works like a charm! 💯

**Comment by toaoscoobs** [comment]
are you able to play the iMessage games on Airmessage??

**Comment by iamroxified** [comment]
> You can change the MIN_OS_VERSION so it looks at the major version number instead of the minor and it works on Monterey. Just did it to test and was able to connect and send messages using my mac with the latest Monterey version

Please where can I change the MIN_OS_VERSION from
